// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Hc2jhjuD9xrBCLa0kLohQjaYuB3NjbU',
    appId: '1:499223119289:web:8c5aa52a7327f4dd0e6268',
    messagingSenderId: '499223119289',
    projectId: 'tiktok-flutter-beem',
    authDomain: 'tiktok-flutter-beem.firebaseapp.com',
    storageBucket: 'tiktok-flutter-beem.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4uIZ2wpI7q4TO6oUnW0CxrgNl-b0ozn4',
    appId: '1:499223119289:android:f2cd3eaacaf230920e6268',
    messagingSenderId: '499223119289',
    projectId: 'tiktok-flutter-beem',
    storageBucket: 'tiktok-flutter-beem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdJ4xjTnMXKjUs4NW9143F26FZ8HQtqII',
    appId: '1:499223119289:ios:5f2c7cd1837e2f160e6268',
    messagingSenderId: '499223119289',
    projectId: 'tiktok-flutter-beem',
    storageBucket: 'tiktok-flutter-beem.appspot.com',
    iosClientId: '499223119289-d9136osvq6o5n30b4dq3uhmnnbdqq2ie.apps.googleusercontent.com',
    iosBundleId: 'com.example.tiktok',
  );
}
